version: '3.8'

services:

  getway:
    build: .
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - my-network
    command: sh -c "npm install && npm run start:dev"

  rabbitmq:
    image:  rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin_password
    container_name: rabbitmq
    hostname: rabbitmq
    volumes: 
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    external: true