version: '3.8'

services:

  getway:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    expose:
      - "3000"
    networks:
      - my-network


networks:
  my-network:
    external: true