version: '3.8'

services:
  quote-service:
    container_name: nestjs-app
    build: .
    ports:
      - '3002:3002'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/nestjsdb

    networks:
      - my-network

  db:
    container_name: nestjs-postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjsdb
    ports:
      - '5432:5432'
    volumes:
      - nestjs-db-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    external: true
    
volumes:
  nestjs-db-data: