version: '3.8'

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  api:
    build: .
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - my-network


networks:
  my-network:
    external: true
volumes:
  mongodb-data:

