version: '3.8'

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    env_file:
      - .env


volumes:
  mongodb-data: