version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27023:27017
    volumes:
      - mongodb_data_container:/data/data_kpi

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3008:3000
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: