version: '3.8'

services:
  claims-database:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    ports:
      - "27019:27017"
    networks:
      - my-network

  api:
    build: .
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - 3007:3007
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - my-network


networks:
  my-network:
    external: true
volumes:
  mongodb-data:

