version: '3.8'
services:
  utils-service-db:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - my-network

  utils-service: 
    build: .
    volumes:
      - .:/utils/src/app
      - /utils/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3005:3005
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - utils-service-db
    networks:
      - my-network

networks:
  my-network:
   external: true

volumes:
  mongodb_data_container: