version: '3.8'
services:
  utils-service-db:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - my-network

  utils-service: 
    build: .
    volumes:
      - .:/app/utils
      - /app/utils/node_modules
    env_file:
      - .env
    ports:
      - 3004:3004
    command: npm run start:dev
    depends_on:
      - utils-service-db
    networks:
      - my-network

networks:
  my-network:
   external: true

volumes:
  mongodb_data_container: