version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - my-network

  api: 
    build: .
    volumes:
      - .:/app/utils
      - /app/utils/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network:
   external: true

volumes:
  mongodb_data_container: