version: '3.8'

services:
  db:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  user-service:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3004:3004
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - my-network


networks:
  my-network:
    external: true
volumes:
  mongodb-data:

