version: '3.8'

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  user-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3004
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - my-network
    command: sh -c "npm install && npm run start:dev"


networks:
  my-network:
    external: true
volumes:
  mongodb-data:

