on:
  push:
    branches: [ 'develop' ]

jobs:
  build:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: feature/deploy

      - name: Setup Node
        uses: actions/setup-node@v1